theme: minima
title: just another science blog
author: kkosal
email: your-email@domain.com
description: Just another guy starting just another science-related blog. Nothing special. Keep scrolling. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
